[phases.setup]
nixPkgs = ['nodejs_18', 'openssl']

[phases.install]
cmds = [
    'npm ci --prefer-offline --no-audit --no-fund --legacy-peer-deps'
]

[phases.build]
cmds = [
    'npx prisma generate',
    'npm run build',
    './scripts/post-build.sh',
    'npm prune --omit=dev'
]

[start]
cmd = './scripts/start-production.sh'
